@echo off
SETLOCAL

REM Generate the Referential Flight protocol.

REM This script allows one to select -upright or -supine with the first parameter.
set posture=%1
set pstr=%posture:~0,1%

set sz=P

REM This script takes an additional input parameter, which is the subject ID. It also inserts this string into the script file name
set id=%2

REM Alias to the compiler.
set COMPILER=DexSimulatorApp.exe
set SOURCE=..\DexSourceCode

REM Task Counter
set task=160
if /I %posture% EQU supine SET task=180 

REM Write a header into the file.
ECHO #DEX protocol file for Parabolic Flight.
ECHO #Generated by %0:  %date% %time%
ECHO #Format: "CMD_TASK", task id, task file, display name


REM ****************************************************************************

REM Standard tasks at the start of a subsession.

REM Perform the install of the equipment in the upright (seated) position.
REM Each subject should do this, even the configuration has changed, to be sure that the CODAs are aligned.
if /I %posture% EQU supine GOTO :SUPINE 
call %SOURCE%\DexCreateInstallTask.bat Upright
GOTO :NEXT
:SUPINE
call %SOURCE%\DexCreateInstallTask.bat Supine
:NEXT

REM Make sure that the audio is set loud enough.
call %SOURCE%\DexCreateAudioTask.bat 

REM The force sensor offsets are also measured and suppressed at the start for each subject.
call %SOURCE%\DexCreateOffsetTask.bat -%posture%  

REM ****************************************************************************

REM
REM Coefficient of Friction tests.
REM

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%FriM
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=1.0 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Moderate

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%FriF
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=2.5 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Firm

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%FriG
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=0.5 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Gentle


REM ****************************************************************************

REM
REM Collisions.
REM

set seq=0
set targets=CollisionSequences20.txt

REM Increment task counter
set /A "task=task+1"
set /A "seq=seq+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%Col%seq%
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -collisionsX -%posture% -targets=%targets%:%seq% -tag=%tag% -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Collisions %seq%

REM Increment task counter
set /A "task=task+1"
set /A "seq=seq+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%Col%seq%
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -collisionsX -%posture% -targets=%targets%:%seq% -tag=%tag% -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Collisions %seq%

REM Increment task counter
set /A "task=task+1"
set /A "seq=seq+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%Col%seq%
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -collisionsX -%posture% -targets=%targets%:%seq% -tag=%tag% -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Collisions %seq%

REM Increment task counter
set /A "task=task+1"
set /A "seq=seq+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%Col%seq%
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -collisionsX -%posture% -targets=%targets%:%seq% -tag=%tag% -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Collisions %seq%

REM Increment task counter
set /A "task=task+1"
set /A "seq=seq+1"
REM Construct a file tag from the above.
set tag=%id%%pstr%Col%seq%
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -collisionsX -%posture% -targets=%targets%:%seq% -tag=%tag% -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Collisions %seq%

REM ****************************************************************************

REM
REM Coefficient of Friction tests.
REM

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%FriM
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=1.0 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Moderate

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%FriF
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=2.5 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Firm

REM Increment task counter
set /A "task=task+1"
REM Construct a file tag from the above.
set tag=%id%FriG
REM Construct a script filename from the tag and task number.
set filename=P%task%%tag%.dex
DexSimulatorApp -friction -filter=2.0 -duration=15.0 -tag=%tag% -pinch=0.5 -compile=%filename%
echo CMD_TASK,%task%,%filename%,%task% Friction Gentle


REM ****************************************************************************

REM
REM Show that protocol is finished.
REM
set /A "task=task+1"
echo CMD_TASK,%task%,TaskFinishProtocol.dex,Finished - press Back

ENDLOCAL
goto :EOF

